export const SET_DEFAULT_BREAD_CRUMB = 'APPLICATION_DETAILS__SET_DEFAULT_BREAD_CRUMB';
export const CLEAR_ALL = 'APPLICATION_DETAIL_FILE__CLEAR_ALL';

export const UPDATE_VALUE = 'APPLICATION_DETAIL_FILE__UPDATE_VALUE';
export const UPDATE_DRAWER_VALUE = 'APPLICATION_DETAIL_FILE__UPDATE_DRAWER_VALUE';
export const CHANGE_FILE_TYPE = 'APPLICATION_DETAIL_FILE__CHANGE_FILE_TYPE';

export const ADD_PATH = 'APPLICATION_DETAIL_FILE__ADD_PATH';
export const REMOVE_PATH = 'APPLICATION_DETAIL_FILE__REMOVE_PATH';
export const UPDATE_PATH = 'APPLICATION_DETAIL_FILE__UPDATE_PATH';
export const UPDATE_DEFAULT_VALUE = 'APPLICATION_DETAIL_FILE__UPDATE_DEFAULT_VALUE';
export const CLEAR_PATH = 'APPLICATION_DETAIL_FILE__CLEAR_PATH';

export const SELECT_ID = 'APPLICATION_DETAIL_FILE__SELECT_ID';
export const OPEN_FOLDER_DRAWER = 'APPLICATION_DETAIL_FILE__OPEN_FOLDER_DRAWER';

export const CLOSE_FOLDER_DRAWER = 'APPLICATION_DETAIL_FILE__CLOSE_FOLDER_DRAWER';
export const OPEN_FILE_DRAWER = 'APPLICATION_DETAIL_FILE__OPEN_FILE_DRAWER';
export const CLOSE_FILE_DRAWER = 'APPLICATION_DETAIL_FILE__CLOSE_FILE_DRAWER';

export const UPDATE_LOADING = 'APPLICATION_DETAIL_FILE__UPDATE_LOADING';

export const FETCH_FILE_INFO = 'APPLICATION_DETAIL_FILE__FETCH_FILE_INFO';
export const UPDATE_FILE = 'APPLICATION_DETAIL_FILE__UPDATE_FILE';
export const UPDATE_FOLDER = 'APPLICATION_DETAIL_FILE__UPDATE_FOLDER';

export const FETCH_BREAD_CRUMB = 'APPLICATION_DETAIL_FILE__FETCH_BREAD_CRUMB';
export const PUSH_BREAD_CRUMB_INFO = 'APPLICATION_DETAIL_FILE__PUSH_BREAD_CRUMB_INFO';
export const FETCH_BREAD_CRUMB_ERROR = 'APPLICATION_DETAIL_FILE__FETCH_BREAD_CRUMB_ERROR';

export const FETCH_LIST = 'APPLICATION_DETAIL_FILE__FETCH_LIST';
export const PUSH_LIST_INFO = 'APPLICATION_DETAIL_FILE__PUSH_LIST_INFO';

// remove
export const REMOVE_RES = 'APPLICATION_DETAIL_FILE__REMOVE_RES';
export const AFTER_REMOVE_RES = 'APPLICATION_DETAIL_FILE__AFTER_REMOVE_RES';

// move
export const OPEN_MOVE_MODAL = 'APPLICATION_DETAIL_FILE__OPEN_MOVE_MODAL';
export const CLOSE_MOVE_MODAL = 'APPLICATION_DETAIL_FILE__CLOSE_MOVE_MODAL';
export const MOVE_RES = 'APPLICATION_DETAIL_FILE__MOVE_RES';
export const AFTER_MOVE_RES = 'APPLICATION_DETAIL_FILE__AFTER_MOVE_RES';
export const UPDATE_MOVE_MODAL_DATA = 'APPLICATION_DETAIL_FILE__UPDATE_MOVE_MODAL_DATA';
export const FETCH_FOLDER_TREE = 'APPLICATION_DETAIL_FILE__FETCH_FOLDER_TREE';
export const PUSH_FOLDER_TREE = 'APPLICATION_DETAIL_FILE__PUSH_FOLDER_TREE';

// search
export const SEARCH_FILES = 'APPLICATION_DETAIL_FILE__SEARCH_FILES';
export const SET_SEARCH_TEXT = 'APPLICATION_DETAIL_FILE__SET_SEARCH_TEXT';

export const CLEAR_LIST = 'APPLICATION_DETAIL_FILE__CLEAR_LIST';
