export const FETCH_APPLICATION_INFO = 'APPLICATION_DETAILS__FETCH_APPLICATION_INFO';
export const FETCH_APPLICATION_INFO_SUCCESS = 'APPLICATION_DETAILS__FETCH_APPLICATION_INFO_SUCCESS';
export const SET_LOADING = 'APPLICATION_DETAILS__SET_LOADING';
